# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- testSetup

pool:
  vmImage: ubuntu-latest


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.17.0'
  displayName: 'Install Node.js'

- script: |
    npm --version
    npm install
    npm run build
  displayName: 'npm install and build'
- script: |
    npm --version
    npm run testFront
    npm run testBack
  env:
    MONGODB_URI: $(MONDODB_URI)
  displayName: 'test runs'
