import Head from "next/head";
import { createContext, useState } from "react";
import "../styles/globals.css";
import { UserContext } from "../utils/UserContext";

function MyApp({ Component, pageProps }) {
	const [user, setUser] = useState(null);

	return (
		<UserContext.Provider value={{ user, setUser }}>
			<Head>
				<title>Building Management</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Component {...pageProps} />
		</UserContext.Provider>
	);
}

export default MyApp;
